### ISSUE TITLE
Mod load order

### ISSUE THREAD

**Issue by suzique725** [mkinfrared/baldurs-gate3-mod-manager#103]
Thank you so much for making this! I just have a question about the mod order section: on the mod manager, the instructions say to "Activate the mods from the Installed Mods list below using Activate button and they will appear here." However, clicking the activate button doesn't add them to the mod order section, nor does it seem to affect their loadout order in any way. Just to be clear, all the mods I've installed thus far _are_ working, I just can't seem to reorder them at all.

**Comment by suzique725** [comment]
Nevermind! Apparently I downloaded the wrong version. Working now

**Comment by cacoots** [comment]
im so confused about what to download...and im having the same problem - what ended up working for you?

**Comment by suzique725** [comment]
Download arm64.dmg, not x64.dmg.

**Comment by cacoots** [comment]
Hey! so there are 2 of them 
<img width="1243" alt="Screenshot 2023-11-04 at 7 29 00 PM" src="https://github.com/mkinfrared/baldurs-gate3-mod-manager/assets/105724955/e8a15a97-033f-415c-9e38-4a90654d591e">
& now im getting this weird screen


<img width="899" alt="Screenshot 2023-11-04 at 7 29 28 PM" src="https://github.com/mkinfrared/baldurs-gate3-mod-manager/assets/105724955/3db3ed2f-22d2-48c3-a89d-13896105a3aa">

**Comment by cacoots** [comment]
@suzique725 I have uninstalled and reinstalled a bunch with both the arm64.dmg (not at the same time haha) but the last img remains :' )

**Comment by suzique725** [comment]
I only downloaded the arm64.dmg file, didn't touch the other ones and it seems to be working just fine. That "weird screen" is just the mod manager, lol. To add mods, go to nexus (or wherever else you want to download mods from,) click the "manual download" option, and drag and drop the the zip files into that box on the right.

**Comment by suzique725** [comment]
<img width="968" alt="Screenshot 2023-11-04 at 4 48 00 PM" src="https://github.com/mkinfrared/baldurs-gate3-mod-manager/assets/91762140/b4fb8fd4-7700-45a5-be27-774132aef0b0">
For example, mine looks like this
