### ISSUE TITLE
Javascript Error When Opening New Update

### ISSUE THREAD

**Issue by cryptiids** [mkinfrared/baldurs-gate3-mod-manager#105]
Since downloading the new mod manager update every time I open it or place in new mods, an error message arrives
"A JavaScript error occurred in the main process" is the title. Message is as follows:

> Uncaught Exception:
> Error: Invalid incoming JSON: PakReader.NotAPackageException: No valid signature found in package file
> at PakReader.PackageReader.Read()
> at Program.<>c.<Main>b__0_0(String )
> PakReader.NotAPackageException: No valid signature found in package file
> at PakReader.PackageReader.Read()
> at Program.<>c.<Main>b__0_0(String )
> PakReader.NotAPackageException: No valid signature found in package file
> at PakReader.PackageReader.Read()
> at Program.<>c.<Main>b__0_0(String )
> {"type":"RESPONSE","response":{"result":"PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4NCjxzYXZlPg0KICAgIDx2ZXJzaW9uIG1ham9yPSI0IiBtaW5vcj0iMCIgcmV2aXNpb249IjAiIGJ1aWxkPSI2OCIvPg0KICAgIDxyZWdpb24gaWQ9IkNvbmZpZyI+DQogICAgICAgIDxub2RlIGlkPSJyb290Ij4NCiAgICAgICAgICAgIDxjaGlsZHJlbj4NCiAgICAgICAgICAgICAgICA8bm9kZSBpZD0iRGVwZW5kZW5jaWVzIi8+DQogICAgICAgICAgICAgICAgPG5vZGUgaWQ9Ik1vZHVsZUluZm8iPg0KICAgICAgICAgICAgICAgICAgICA8YXR0cmlidXRlIGlkPSJBdXRob3IiIHR5cGU9IkxTV1N0cmluZyIgdmFsdWU9InhkaXNzaWRpYXgta2FydCIvPg0KICAgICAgICAgICAgICAgICAgICA8YXR0cmlidXRlIGlkPSJDaGFyYWN0ZXJDcmVhdGlvbkxldmVsTmFtZSIgdHlwZT0iRml4ZWRTdHJpbmciIHZhbHVlPSIiLz4NCiAgICAgICAgICAgICAgICAgICAgPGF0dHJpYnV0ZSBpZD0iRGVzY3JpcHRpb24iIHR5cGU9IkxTV1N0cmluZyIgdmFsdWU9IkN1c3RvbSBIZWFkIFByZXNldHMiLz4NCiAgICAgICAgICAgICAgICAgICAgPGF0dHJpYnV0ZSBpZD0iRm9sZGVyIiB0eXBlPSJMU1dTdHJpbmciIHZhbHVlPSJkaXNzaWRpYV9tYWxlX2JlYXV0eV9jb2xsZWN0aW9uIi8+IA0KICAgICAgICAgICAgICAgICAgICA8YXR0cmlidXRlIGlkPSJHTVRlbXBsYXRlIiB0eXBlPSJGaXhlZFN0cmluZyIgdmFsdWU9IiIvPg0KICAgICAgICAgICAgICAgICAgICA8YXR0cmlidXRlIGlkPSJMb2JieUxldmVsTmFtZSIgdHlwZT0iRml4ZWRTdHJpbmciIHZhbHVlPSIiLz4NCiAgICAgICAgICAgICAgICAgICAgPGF0dHJpYnV0ZSBpZD0iTUQ1IiB0eXBlPSJMU1N0cmluZyIgdmFsdWU9IiIvPg0KICAgICAgICAgICAgICAgICAgICA8YXR0cmlidXRlIGlkPSJNYWluTWVudUJhY2tncm91bmRWaWRlbyIgdHlwZT0iRml4ZWRTdHJpbmciIHZhbHVlPSIiLz4NCiAgICAgICAgICAgICAgICAgICAgPGF0dHJpYnV0ZSBpZD0iTWVudUxldmVsTmFtZSIgdHlwZT0iRml4ZWRTdHJpbmciIHZhbHVlPSIiLz4NCiAgICAgICAgICAgICAgICAgICAgPGF0dHJpYnV0ZSBpZD0iTmFtZSIgdHlwZT0iRml4ZWRTdHJpbmciIHZhbHVlPSJkaXNzaWRpYV9tYWxlX2JlYXV0eV9jb2xsZWN0aW9uIi8+DQogICAgICAgICAgICAgICAgICAgIDxhdHRyaWJ1dGUgaWQ9Ik51bVBsYXllcnMiIHR5cGU9InVpbnQ4IiB2YWx1ZT0iNCIvPg0KICAgICAgICAgICAgICAgICAgICA8YXR0cmlidXRlIGlkPSJQaG90b0Jvb3RoIiB0eXBlPSJGaXhlZFN0cmluZyIgdmFsdWU9IiIvPg0KICAgICAgICAgICAgICAgICAgICA8YXR0cmlidXRlIGlkPSJTdGFydHVwTGV2ZWxOYW1lIiB0eXBlPSJGaXhlZFN0cmluZyIgdmFsdWU9IiIvPg0KICAgICAgICAgICAgICAgICAgICA8YXR0cmlidXRlIGlkPSJUYWdzIiB0eXBlPSJMU1dTdHJpbmciIHZhbHVlPSIiLz4NCiAgICAgICAgICAgICAgICAgICAgPGF0dHJpYnV0ZSBpZD0iVHlwZSIgdHlwZT0iRml4ZWRTdHJpbmciIHZhbHVlPSJBZGQtb24iLz4NCgkJCQkJPGF0dHJpYnV0ZSBpZD0iVVVJRCIgdHlwZT0iRml4ZWRTdHJpbmciIHZhbHVlPSJkMTY3OWI5MS00NDMwLTQ4YjItYjUxOC1hNDc4OTUwY2M1ZDMiLz4NCiAgICAgICAgICAgICAgICAgICAgPGF0dHJpYnV0ZSBpZD0iVmVyc2lvbjY0IiB0eXBlPSJpbnQ2NCIgdmFsdWU9IjM2MDI4Nzk3MDE4OTYzOTY4Ii8+DQogICAgICAgICAgICAgICAgICAgIDxjaGlsZHJlbj4NCiAgICAgICAgICAgICAgICAgICAgICAgIDxub2RlIGlkPSJQdWJsaXNoVmVyc2lvbiI+DQogICAgICAgICAgICAgICAgICAgICAgICAgICAgPGF0dHJpYnV0ZSBpZD0iVmVyc2lvbjY0IiB0eXBlPSJpbnQ2NCIgdmFsdWU9IjM2MDI4Nzk3MDE4OTYzOTY4Ii8+DQogICAgICAgICAgICAgICAgICAgICAgICA8L25vZGU+DQogICAgICAgICAgICAgICAgICAgICAgICA8bm9kZSBpZD0iU2NyaXB0cyIvPg0KICAgICAgICAgICAgICAgICAgICAgICAgPG5vZGUgaWQ9IlRhcmdldE1vZGVzIj4NCiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8Y2hpbGRyZW4+DQogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxub2RlIGlkPSJUYXJnZXQiPg0KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPGF0dHJpYnV0ZSBpZD0iT2JqZWN0IiB0eXBlPSJGaXhlZFN0cmluZyIgdmFsdWU9IlN0b3J5Ii8+DQogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDwvbm9kZT4NCiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8L2NoaWxkcmVuPg0KICAgICAgICAgICAgICAgICAgICAgICAgPC9ub2RlPg0KICAgICAgICAgICAgICAgICAgICA8L2NoaWxkcmVuPg0KICAgICAgICAgICAgICAgIDwvbm9kZT4NCiAgICAgICAgICAgIDwvY2hpbGRyZW4+DQogICAgICAgIDwvbm9kZT4NCiAgICA8L3JlZ2lvbj4NCjwvc2F2ZT4=","id":"ada50c8b-00e5-4c0b-8ec4-240f43685ea2"}}
> at TabSeparatedInputStreamParser.addPartial (/private/var/folders/0c/1wzvq79x26q97cz2zf1pd57m0000gn/T/AppTranslocation/DF8CF2E0-7511-41CE-8230-F5F0B1C90753/d/Baldur's Gate 3 Mod Manager.app/Contents/Resources/app.asar/node_modules/electron-cgi/tab-separated-input-stream-parser.js:16:23)
> at Socket.<anonymous> (/private/var/folders/0c/1wzvq79x26q97cz2zf1pd57m0000gn/T/AppTranslocation/DF8CF2E0-7511-41CE-8230-F5F0B1C90753/d/Baldur's Gate 3 Mod Manager.app/Contents/Resources/app.asar/node_modules/electron-cgi/connection.js:13:27)
> at Socket.emit (node:events:514:28)
> at addChunk (node:internal/streams/readable:324:12)
> at readableAddChunk (node:internal/streams/readable:293:11)
> at Socket.push (node:internal/streams/readable:234:10)
> at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)

- Manager Version : v1.4.2
- Operating System and version : mac os montrery v12.0.1

**Comment by cryptiids** [comment]
Went through previous versions, error showed on all up until v1.3.0

**Comment by mkinfrared** [comment]
Which mod were you trying to install?

**Comment by cryptiids** [comment]
> Which mod were you trying to install?

Wow I'm so sorry it was the dumbest thing on my end, my game hadn't updated!
