### ISSUE TITLE
Configuring modsettings.lsx

### ISSUE THREAD

**Issue by GravenTec** [mkinfrared/baldurs-gate3-mod-manager#112]
## Summary
When utilizing the tool files are unpacked and relocated to the appropriate folder normally. 
I see the file modsettings.lsx needs to be set to read/write and then locked or the game overwrites it with the default settings. 
Allowing the tool to populate it and then resetting it to read only appears to work, however, the game does not recognize mods. 

When inspecting the modsettings.lsx file I see that the last line of the config is unpopulated 
attribute id="Version64" type="" value="" 
Comparison from 5e spells:
attribute id="Version64" value="36169534507319307" type="int64"
Is there a step missing or?

**Comment by mkinfrared** [comment]
I checked that mod, and yes it is using Version64 attribute instead of just simple Version, I will address that discrepancy in the future release

**Comment by mkinfrared** [comment]
but I assume the mod should still work event if the version is missing. tell me if I'm wrong

**Comment by GravenTec** [comment]
In that Example: The mods all worked when i was building the file manually, however, no mod loads as entered by the tool at this time. 
IE none of the mod entries to modsettings.lsx have : attribute id="Version64" type="" value="". populated. 

Going to try and edit them all manually and see if that makes a difference (  type="int64" may make a difference )

**Comment by GravenTec** [comment]
Appears some fields are being populated with latest Version Change (see attached screenshots.) 
Mods not loading as of yet, will ensure is not user error. 
![image](https://github.com/mkinfrared/baldurs-gate3-mod-manager/assets/150306874/008eb042-d177-4fd3-9be4-faaeaf8e8e6a)
![image](https://github.com/mkinfrared/baldurs-gate3-mod-manager/assets/150306874/f9d099ca-094c-47c5-8971-e9c2108dd1de)
![Screenshot 2023-11-09 at 10 44 02 AM](https://github.com/mkinfrared/baldurs-gate3-mod-manager/assets/150306874/158d50d0-638b-4494-a8d6-a549eb0880ef)
![Screenshot 2023-11-09 at 10 44 02 AM](https://github.com/mkinfrared/baldurs-gate3-mod-manager/assets/150306874/a6ca20a5-4380-4146-ac50-92a511cb7e68)

**Comment by mkinfrared** [comment]
I addressed that discrepancy with version/version64. I will release a new version with that fix soon. You should see an update window when it’s ready. Let me know if that fixed your problem

**Comment by GravenTec** [comment]
will check for update (tested with 1.4.3), attempted manual update of int64: does not appear to load. Checking modsettings.lsx compared to old manual configuration backups.

**Comment by mkinfrared** [comment]
relaunch the app, it should prompt you to download a new version

**Comment by GravenTec** [comment]
Deleted and reinstalled app (running V1.4.4 ARM Version), deactivated and reactivated mods as test. Checked modsettings.lsx and launched via Larion launcher. Mods not loading.

**Comment by mkinfrared** [comment]
are you talking about 5e spells?

**Comment by mkinfrared** [comment]
Did you try to activate them one at a time? Also some mods require a specific load order, you can change it with a drag and drop

**Comment by GravenTec** [comment]
> Did you try to activate them one at a time? Also some mods require a specific load order, you can change it with a drag and drop

Attempted bulk activation, will attempt launch with one mod activated, odd thing is some mods aren't dependent are also not loading. Possible that the action "breaks" at the point of the out of order mod and causes all to fail loading.

**Comment by GravenTec** [comment]
Singular activation of two stable mods successful. 
Suspect you hit the nail on the head, i believe the issue to be on my end related to a combination of load order and possible a missing framework (supporting mod such as how susser req JWL Crafting Framework). Odd part is i have them there, but may not be the right versions. 

Will troubleshoot further on my end, Type and Value bug confirmed resolved.
