### ISSUE TITLE
Mods won't get activated

### ISSUE THREAD

**Issue by hushhushlynn** [mkinfrared/baldurs-gate3-mod-manager#114]
## Your Environment

- Manager Version : v1.4.3
- Link to problem mod :
- Operating System and version :macOS Monterey Version 12.6

Hi, I installed the newest Mod Manager and downloaded one mod and installed it, now my Mod Manager looks like this, and I clicked on "Activate" button many times but there's no reaction. I tried to open the game but it's stuck - it shows the game is 100% loaded but won't open. Could you please tell me how can I fix it?
![image](https://github.com/mkinfrared/baldurs-gate3-mod-manager/assets/150380179/b56b3217-1da3-4247-82e8-4d3fcf4870d7)

**Comment by mkinfrared** [comment]
there's something wrong with your modsettings file. you can paste its content here, so I could see what's the issue there

**Comment by hushhushlynn** [comment]
Here's the mods folder: Baldur's Gate 3 - Mods:
![image](https://github.com/mkinfrared/baldurs-gate3-mod-manager/assets/150380179/5707d294-05f6-4d78-b7ba-beb862c93515)

and here's the modsetting file: Baldur's Gate 3 - PlayerProfiles - Public:
![image](https://github.com/mkinfrared/baldurs-gate3-mod-manager/assets/150380179/48118068-3632-4971-8d42-d8e9c2eb6c82)

don't know why but the mod settings.lsx file is 0bytes....
![image](https://github.com/mkinfrared/baldurs-gate3-mod-manager/assets/150380179/31440836-b221-45b5-98e9-8e32e915dd34)

**Comment by mkinfrared** [comment]
open your modsettings.lsx file in any editor, standard TextEdit should work, and paste it here

**Comment by hushhushlynn** [comment]
yeah it's definitely wrong......it's empty........

**Comment by hushhushlynn** [comment]
ok I copy & paste some code from internet and seems the mods work now - but not really:
![image](https://github.com/mkinfrared/baldurs-gate3-mod-manager/assets/150380179/324847b5-d4f8-405d-b35d-b5c8f455f380)
