### ISSUE TITLE
Mods saying they are activated when they aren't or the activate button doesn't work at all

### ISSUE THREAD

**Issue by RinaBBfly** [mkinfrared/baldurs-gate3-mod-manager#130]
I have a similar problem to whereisbunbun had before, so I'll try to explain it as best as possible.

This mod manager had been working flawlessly since the Patch 4 update when I installed it. However, when I start the game now, it says that all the mods had been disabled and at one point when I went into the mod manager, none of the activate or disable buttons were working.

I tried to see if it had to do something with the modsettings file being locked but it had been unlocked the entire time. I'm not sure if the modsettings file is resetting every time I open the game but it's weird that it's doing it when I haven't done anything different whatsoever. I haven't added any mods but only deleted a few but I'm not sure how that would have changed anything.

I'm not sure if it's the mod manager or something on my end.

I even tried copying and pasting what you had sent them to replace in the modsettings file but that didn't work either.

Also, the game gets stuck at 100% when starting. I seriously haven't done anything different this time so I'm super confused why this is happening.

Help is appreciated, of course.

**Comment by mkinfrared** [comment]
You can try this fix

https://github.com/mkinfrared/baldurs-gate3-mod-manager#troubleshoot

**Comment by RinaBBfly** [comment]
It worked! Thanks so much!
