### ISSUE TITLE
Mods are not being installed.

### ISSUE THREAD

**Issue by roseheira** [mkinfrared/baldurs-gate3-mod-manager#71]
## Summary

I've been trying to install mods using this mod manager but for some reason nothing happens when I do? I don't know if I'm doing something wrong or if it's simply not working for me, because once I click 'install' it'd do absolutely nothing, lol. The mods showing in the screenshot were installed manually, if it helps.

<img width="1076" alt="Captura de Pantalla 2023-10-14 a la(s) 10 11 49 p m" src="https://github.com/mkinfrared/baldurs-gate3-mod-manager/assets/147962864/320d33d7-a8a5-42db-9dd3-cae74f9a9a04">

**Comment by azwargamer** [comment]
Are the pak files not being moved to the mods folder or is that happening but the modsettings file isn’t being updated? If it’s the latter issue, check to confirm there is a json file.

**Comment by roseheira** [comment]
The pak files are not being moved to the mods folder, even though they do have a json file. I will continue to check with other mods but yeah, so far I haven't had any luck because the manager doesn't do anything.

**Comment by roseheira** [comment]
Update: I've resolved the problem, I just needed to unlock and put on read & write my modsettings.lsx file! It works perfectly now.

**Comment by nilcolor** [comment]
I have the same issue when tried to install https://www.nexusmods.com/baldursgate3/mods/1279 mod. modsettings.lsx is not locked and it was initially created by mods manager.
I suspect the issue is that mod have no json, etc. Just a few xaml files inside. IS this assumption correct?
